'use strict';

const CreateBoomError = require('create-boom-error').bind(exports);

// boom errors
CreateBoomError('AtLeastOneDex', 422, 'at least 1 dex is required for an account');
CreateBoomError('EmptySlug', 422, 'the URL generated by the title needs at least one alphanumeric character');
CreateBoomError('ExistingDex', 422, 'a dex with that URL already exists, please try a different title');
CreateBoomError('ExistingUsername', 422, 'username is already taken');
CreateBoomError('ForbiddenAction', 403, (action) => `${action} is not allowed`);
CreateBoomError('InvalidPassword', 422, 'password is invalid');
CreateBoomError('NotFound', 404, (item) => `${item} not found`);
CreateBoomError('UnprocessableEntity', 422, (message) => message);

// postgres errors
exports.DuplicateKey = (err) => err.message.includes('duplicate key value');

// stripe errors
exports.GenericStripe = (err) => err.type && err.type.indexOf('Stripe') === 0;
