INSERT INTO games VALUES
('red', 'Red', 'red_blue', 1),
('blue', 'Blue', 'red_blue', 2),
('yellow', 'Yellow', 'yellow', 3),
('gold', 'Gold', 'gold_silver', 4),
('silver', 'Silver', 'gold_silver', 5),
('crystal', 'Crystal', 'crystal', 6),
('ruby', 'Ruby', 'ruby_sapphire', 7),
('sapphire', 'Sapphire', 'ruby_sapphire', 8),
('fire_red', 'FireRed', 'fire_red_leaf_green', 9),
('leaf_green', 'LeafGreen', 'fire_red_leaf_green', 10),
('emerald', 'Emerald', 'emerald', 11),
('diamond', 'Diamond', 'diamond_pearl', 12),
('pearl', 'Pearl', 'diamond_pearl', 13),
('platinum', 'Platinum', 'platinum', 14),
('heart_gold', 'HeartGold', 'heart_gold_soul_silver', 15),
('soul_silver', 'SoulSilver', 'heart_gold_soul_silver', 16),
('black', 'Black', 'black_white', 17),
('white', 'White', 'black_white', 18),
('black_2', 'Black 2', 'black_2_white_2', 19),
('white_2', 'White 2', 'black_2_white_2', 20),
('x', 'X', 'x_y', 21),
('y', 'Y', 'x_y', 22),
('omega_ruby', 'Omega Ruby', 'omega_ruby_alpha_sapphire', 23),
('alpha_sapphire', 'Alpha Sapphire', 'omega_ruby_alpha_sapphire', 24),
('sun', 'Sun', 'sun_moon', 25),
('moon', 'Moon', 'sun_moon', 26),
('ultra_sun', 'Ultra Sun', 'ultra_sun_ultra_moon', 27),
('ultra_moon', 'Ultra Moon', 'ultra_sun_ultra_moon', 28)
;
